---
- hosts: dockerservers:kubernetesservers
  become: yes
  strategy: free
  tasks:
  - name: Remove old docker [1/3]
    apt:
      name: docker
      state: absent
  - name: Remove old docker [2/3]
    apt:
      name: docker-engine
      state: absent
  - name: Remove old docker [3/3]
    apt:
      name: docker.io
      state: absent

  - name: Register apt key
    apt_key: url="https://download.docker.com/linux/ubuntu/gpg" id="9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    when: ( ansible_distribution == "Ubuntu" or ansible_lsb["id"] == "Raspbian" )

  - name: Register apt source [Ubuntu]
    shell: echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
    args:
      creates: /etc/apt/sources.list.d/docker.list
    when: ( ansible_distribution == "Ubuntu" )

  - name: Register apt source [Raspbian]
    shell: echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/raspbian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    args:
      creates: /etc/apt/sources.list.d/docker.list
    when: ( ansible_lsb["id"] == "Raspbian" )

  - name: Install docker package
    apt:
      name: docker-ce
      state: latest
      update_cache: true
    when: ( ansible_distribution == "Ubuntu" or ansible_lsb["id"] == "Raspbian" )
